= Intro to JPA

Реализовать приложение *Messenger*.

== Specification of task 1

Настроить проект для работы с *JPA*. Для этого необходимо:

* Создать maven-проект.
* Подключить зависимости *Driver*, *JPA*, *EclipseLink* (одной из реализаций *JPA*).
* Настроить работу *JPA* (в частности *EclipseLink*) с помощью `persistence.xml`.

== Specification of task 2

Создать и произвести маппинг Class to Table. Для этого необходимо:

* Создать класс Entity `Message` с полями:
** `id`
** `text`,
* произвести _mapping_ _class_ на _table_ с помощью xml-files.

== Specification of task 3

Реализовать DAO класс, который может при помощи `EntityManager`:

* сохранять объекта в _database_
* получать объекта из _database_

== Specification of task 4

Протестировать работу методов в DAO классе. Для этого необходимо:

* Подключить тестовые зависимости *JUnit 5* и *Testcontainers* к проекту.
* Создать _configuration_ проекта для тестов, используя в качестве СУБД *PostgreSQL* в *Testcontainers*.
* Реализовать unit-тесты для всех методов.

== Specification of task 5

Упростить работу по написанию *boilerplate code* (*шаблонного кода*). Для этого необходимо:

* Подключить зависимость *Project Lombok* к проекту.
* Переписать класс `Message`, используя lombok-аннотации.
