= Restaurant

Реализовать _CLI_ клиента для работ c *Restaurant*.
Данные для него хранятся в _DBSM_, SQL script для создания необходимой структуры _DB_ приведен ниже:

:source: ../../../../../../../src

[source,sql]
----
include::../sql/restaurant.sql[SQL script]
----

_CLI_ клиент содержит меню, в котором находятся доступные для пользователя команды (функциональность).

== Task 1

Создать _entity_ `Restaurant` которая содержит поля:
- `id`
- `name`

== Task 2

Создать _DAO_ для _entity_ `Restaurant`. Добавить в его метод, который позволяет сохранять _entity_ `Restaurant` в _DB_.
Метод должен возвращать сохраненную _entity_ `Restaurant`,  т.е. _entity_ с установленым `id`.

== Task 3

Создать _entity_ `Review` которая содержит поля:
- `id`
- `content`
- `restaurant`

== Task 4

Создать _DAO_ для _entity_ `Review`. Добавить в его метод, который позволяет сохранять _entity_ `Review` в _DB_.
Метод должен возвращать сохраненную _entity_ `Review`, т.е. _entity_ с установленым `id`.

== Task 5

Создать _entity_ `Dish` которая содержит поля:
- `id`
- `name`

== Task 6

Модифицировать _entity_ `Restaurant`, чтобы он содержал коллекцию `Dish`.

== Task 7

Модифицировать _DAO_ для _entity_ `Restaurant`. Добавить в его метод, который позволяет сохранять _entity_ `Dish` для
данного ресторана в _DB_. Метод должен возвращать сохраненную _entity_ `Dish`, т.е. _entity_ с установленым `id`.

== Task 8

Модифицировать _entity_ `Restaurant`, чтобы он содержал коллекцию `Review`.

== Task 9

Модифицировать _DAO_ для _entity_ `Restaurant`. Добавить в его метод, который позволяет сохранять _entity_ `Review` для
данного ресторана в _DB_. Метод должен возвращать сохраненную _entity_ `Review`, т.е. _entity_ с установленым `id`.

== Task 10

Модифицировать _DAO_ для _entity_ `Restaurant`. Добавить в его метод, который позволяет возвращать _entity_ `Restaurant`
с помощью `id`, а так же с полными колекциями `Dish` и `Review` для данного `Restaurant`.
