= Intro to Hibernate

Реализовать приложение "Каталог для картин".

== Specification of task 1

Настроить проект для работы с *Hibernate*. Для этого необходимо:

* Создать maven-проект.
* Подключить зависимости *Driver*, *JPA*, *Hibernate* (одной из реализаций *JPA*).
* Настроить работу *Hibernate* с помощью `hibernate.cfg.xml`.

== Specification of task 2

Создать и произвести маппинг Class to Table. Для этого необходимо:

* Создать класс Entity `Painting` с _fields_:
* `id`
* `name`
* `authorName`
* произвести _mapping_ _class_ на _table_ с помощью аннотаций.

== Specification of task 3

Реализовать DAO класс, который может следующие операции над *Entity* при помощи `Session`:

* сохранить
* найти
** с помощью id
** все
* обновить
* удалить

Каждый методы выполняются в собственной `Transaction`.

== Specification of task 4

* Подключить dependency *Log4J2* - библиотека для _logging_.
* Настроить *Log4J2* с помощью `log4о2.чьд` для вывода в Standard Output.

== Specification of task 5

Протестировать работу методов в DAO классе. Для этого необходимо:

* Подключить тестовые зависимости *JUnit 5* и *Testcontainers* к проекту.
* Создать _configuration_ проекта для тестов, используя в качестве СУБД *PostgreSQL* в *Testcontainers*.
* Реализовать unit-тесты для всех методов.
